### ISSUE TITLE
How to make it immediate ?

### ISSUE THREAD

**Issue by tferreira** [GamingBud/DefChat#1]
Hi,

First of all, very nice plugin 👍 

I tried changing a few vars to make the chat display messages immediately, but I'm not sure that I understand every part of it. I'm probably doing mistakes but I changed this:

```	
       - self.actStamp[1] = true; self.actStamp[2] = false

       + self.actStamp[1] = true; self.actStamp[2] = true
```

So, messages display immediately but I'm having this error:

```
ERROR:SCRIPT: /DefChat/DefChat.gui_script:316: bad argument #1 to 'len' (string expected, got nil)
stack traceback:
	[C]: in function 'len'
	/DefChat/DefChat.gui_script:316: in function 'stamp'
	/DefChat/DefChat.gui_script:90: in function </DefChat/DefChat.gui_script:84>
```

Any idea on how I can make it cleaner please ?

**Comment by GamingBud** [comment]
Hey there! Thanks for reporting this. I didn't test out the instant mode with the newest version. It was an 'Oopsie' on my part. It was the cause of a missing 'else' statement, so a part of the stamping function ran when it wasn't supposed to ;). I just uploaded the fixed version.

I agree, my coding is definitely not optimal for understanding yet. Now that it's working correctly and someone's taken interest in it, I'll use the knowledge I gained over the past few months to make things more optimized.

**Comment by tferreira** [comment]
No worries, it's already cool that you shared this.
I tried the fixed version and it's in "instant mode" like I was expecting.

But I'm not sure `instant = false` nor `self.typeSpeed` are working though, for those who want the old behaviour:
`typeSpeed` is delaying the entire message but not the letters one by one, and `instant` has no effect.

**Comment by GamingBud** [comment]
That's odd. Instant = false works on my end. You have to change the variable at the end of the buildMessage(). It will be a line as such:

self.actStamp.go = true; self.actStamp.instant = true

Honestly, I don't understand why I made this so awkward. I'll most definitely make many improvements soon. And about the typeSpeed bug, I'll have to look into why that would be.

**Comment by tferreira** [comment]
Indeed, I was changing the wrong one. Thank your for the fix and the feedback :)
(You may close the issue.)

**Comment by GamingBud** [comment]
self.actStamp is now self.stamp_text, and the self.stamp_text.instant variable has been moved to initialization where it's more suitable.
