### ISSUE TITLE
Error on input

### ISSUE THREAD

**Issue by tferreira** [GamingBud/DefChat#4]
FYI, latest master gives me this error:

```
ERROR:SCRIPT: /DefChat/DefChat.gui_script:148: attempt to compare nil with number
stack traceback:
	/DefChat/DefChat.gui_script:148: in function </DefChat/DefChat.gui_script:110>
```

**Comment by GamingBud** [comment]
I set aside a properties module for DefChat to hook to that will not be overwritten every update. This allows you to make modifications, and not have those set back to the default for every update.

Inside master, there's a file named "DefChat_Properties". Download that and place it in your main folder. This will solve it, although if it doesn't for some reason, let me know.

**Comment by tferreira** [comment]
This line has been removed the `init()`, and it works fine if I add it again:
```
self.lineWidth = self.clProperties.width - (self.clProperties.width/15)
```
