### ISSUE TITLE
Support for accented/special characters

### ISSUE THREAD

**Issue by tferreira** [GamingBud/DefChat#7]
Hi,

I noticed we can't type accented characters (important for a lot of languages).
I tried a few things but still not managed to make it work with special characters :

- There will be an issue with DefChat code as accented/special characters length is > 1.
- On my tests, defold GUI displays special characters with an `~`

I would like to have your input on this until I have time to do more research, and come up with a solution or a pull request ;)

Thanks.

**Comment by GamingBud** [comment]
> - There will be an issue with DefChat code as accented/special characters length is > 1.
Ok, this could be solved by running a check as soon as keys are pressed. I'll run an if statement that checks if the size is going over the length of the chat box, and then act accordingly.

> - On my tests, defold GUI displays special characters with an ~
This is to do with the font used. Defold, by default, displays characters that are not in the font as a tilde.

I'll see if I can get this working soon.

**Comment by GamingBud** [comment]
@tferreira Before I go into all the work of programming in a table of alt-sequence values, how are you inputting special characters? Are you using Alt-Sequence or a keyboard which has special characters instead of English characters?

**Comment by tferreira** [comment]
I'm using an EU keyboard with AZERTY layout.

**Comment by GamingBud** [comment]
@tferreira DefChat was just updated to version .560, in which I added functionality for special characters. Let me know if you find any problems.

**Comment by tferreira** [comment]
Should it work by just checking the "All chars" box of the _**system_font**_ ?
I'm still having those "~" appearing in place of special chars.

By the way, if I add a new font in my DefChat_properties.lua, I still have to add it to the DefChat.gui file right ?

**Comment by tferreira** [comment]
Thank you for the new version !
I can't use DefChat as a dependency when I add a new font to DefChat.gui though.

I tried it and most of the characters are working. The `^` alone for example is not working.
Also, when I type an accented letter such as `à`, when I do a backspace to remove it, it's not removing it completely. It displays a weird `Â` letter that I also have to erase.

**Comment by tferreira** [comment]
> I can't use DefChat as a dependency when I add a new font to DefChat.gui though.

> Yes, that would be a caveat, but I don't think I can do anything about that :/.

Yeah, that would mean adding the system font with "extra chars: activated" into DefChat, but for me it's okay, I can add it on my fork.

**Comment by GamingBud** [comment]
> Yeah, that would mean adding the system font with "extra chars: activated" into DefChat, but for me it's okay, I can add it on my fork.

True. I meant that I can't do anything about users adding _new_ fonts.

**Comment by GamingBud** [comment]
**_Special characters support broke._** I have no idea what happened.

Working on fixing this ASAP. Once that's done, I'll see about fixing the duplicants and implementing the default font.

**Comment by GamingBud** [comment]
These issues should be solved. I just pushed Update .670.

I'll let you close this, in case you run into any more issues.

**Comment by tferreira** [comment]
Thank you very much! That's awesome!
I just noticed that the cursor doesn't move when I use the spacebar, until I write another letter.

I also changed the color on the properties file to have the green color back, but this is personal preference:
`		
in_frame = vmath.vector4(.4,.6,.4,1),
in_commandline = vmath.vector4(.4,.6,.4,1)
`

Is it in purpose that the font is of size 14 ?

**Comment by GamingBud** [comment]
@tferreira 
> I just noticed that the cursor doesn't move when I use the spacebar, until I write another letter.  
That's to do with the gui.get_text_metrics function. It doesn't include spaces in it's calculation, apparently, unless it's between two words/letters. I'll see if I can make a workaround for this in the next update.

> Is it in purpose that the font is of size 14 ?  
No, that was the default for that font, I believe. DefChat will adjust itself for whatever size is given.
